### ISSUE TITLE
Opus Codec

### ISSUE THREAD

**Issue by ghost** [martindevans/MumbleSharp#15]
Please make the Opus codec functional, as MumbleSharp seems to prefer using it.

**Comment by martindevans** [comment]
Ping for MrRatermat - Opus is *half* supported (receiving/decoding, but not recording/encoding/transmitting). Hopefully I'll get some time to implement the other half of Opus support soon (and double hopefully support for other codecs will follow up soon after that).

**Comment by chaozznl** [comment]
I'm eager to see progress on this. Keep me posted!

**Comment by Meetsch** [comment]
Hi Martin, you should close this ticket as Opus ecording/encoding/transmitting is working great by now.
