### ISSUE TITLE
Voice Packet Malformed

### ISSUE THREAD

**Issue by martindevans** [martindevans/MumbleSharp#17]
Voice encoding does not properly format outgoing voice packets. MumbleConnection.cs:

```
public void SendVoice(ArraySegment<byte> packet)
{
    _tcp.Send(PacketType.UDPTunnel, packet);
}
```

This simply sends the encoded data.... but makes no effort to build the correct format of packet _around_ the encoded data!

**Comment by scott-plutovr** [comment]
I am going to start looking into this issue but it certainly seems like the packet needs to be properly formatted based on this specification [1].

**Comment by Meetsch** [comment]
Hi, looking at the code the BasicMumbleProtocol EncodingThread is forming the packet correctly. So I changed the warning comment in PR #47
