### ISSUE TITLE
Channel Names Being Lost in BasicMumbleProtocol

### ISSUE THREAD

**Issue by OptrixAU** [martindevans/MumbleSharp#23]
Channel names are being lost when the ChannelState message doesn't include a name.

The solution is very simple - just check that the property is specified before you replace it. 

In the ChannelState function in **BasicMumbleProtocol.cs**, change...

`c.Name = channelState.name;`

To 

`if (channelState.nameSpecified)
     c.Name = channelState.name; 
`

**Comment by OptrixAU** [comment]
I don't currently have the source checked out in Git, so I can't push an update up at the moment.

**Comment by martindevans** [comment]
You're absolutely right.

In a broader sense there are probably little bugs like this all over the place. One of the changes I made last time I was working on Mumble# was to auto generate all the packet classes (such as channel state) from the protocol buffer specification. Previously I had been writing them by hand and didn't have the utility properties such as ```nameSpecified``` so I've probably missed out checks like this all over!

**Comment by Meetsch** [comment]
fixed in PR #47 I used the now available protobuf's ShouldSerialize to fix those kinds of issues in ChannelState, PermissionQuery and ServerSync (I didn't spot any other implemented protocol message receptions with such possible problems)
