### ISSUE TITLE
MumbleGuiClient avoid continuously sending voice

### ISSUE THREAD

**Issue by Meetsch** [martindevans/MumbleSharp#33]
Hi, I'll be working to improve the MumbleGuiClient to send voice only when the microphone volume level is above a threshold.
Therefore the voice will not be sent to murmur when the microphone is nearly silent.

**Comment by Meetsch** [comment]
Work already done, waiting for existing pull-requests to be accepted before submitting this new one.

**Comment by martindevans** [comment]
How are you planning on implementing this? What you really need is to implement a full [voice activity detector](https://en.wikipedia.org/wiki/Voice_activity_detection) (VAD). A basic volume threshold can be _ok_ as there's a hold time (i.e. you need a duration of silence before transmission stops). Ideally we'd use something like the VAD algorithm from webRTC, but that's pretty big and complex and is well beyond the scope of this project!

**Comment by Meetsch** [comment]
Hi, I've sent you a pull request for the minimal microphone volume level (threshold with hold time) feature in the MumbleGuiClient example. Here is the pull request: https://github.com/martindevans/MumbleSharp/pull/35
