### ISSUE TITLE
Sound can be listened only for first time for user

### ISSUE THREAD

**Issue by buldo** [martindevans/MumbleSharp#39]
I've tested MumbleClient app with local Murmur server and Plumble client on my smartphone.
Each time I've started speaking via Plumble I had new sequence of voice packages that started from 0 sequence number.

Because of this check
https://github.com/martindevans/MumbleSharp/blob/f145fed118c2327089f2b3ff4a03fea69440f458/MumbleSharp/Audio/AudioDecodingBuffer.cs#L68
I able to hear voice via MumbleClient only from first transmission. Or then new transmission is longer than previous

**Comment by martindevans** [comment]
That definitely looks like the culprit. When speech ends or a new speech session starts that event should be detected and used to reset the sequence number. I'm not sure what the best way to do that would be otoh.

I don't really have time to investigate this, but I will be happy to review a pull request to fix this :)

**Comment by buldo** [comment]
I don know how to detect end of transmission or start of new transmission. 
I use dirty hack in my project - 100ms timer, that resets counter if there is no new packages.

**Comment by Meetsch** [comment]
fixed in PR #47 by resetting the _nextSequenceToDecode  when sequence == 0

**Comment by Meetsch** [comment]
Hi @buldo ,
Can you please report if our fix did effectively solve your issue with Plumble client. Thanks.

**Comment by buldo** [comment]
Unfortunately I can not because I use heavily modified version of this library in my project.
