### ISSUE TITLE
FiveM and other Mumble Compliant Services

### ISSUE THREAD

**Issue by DrewRidley** [martindevans/MumbleSharp#58]
Good evening,

I have recently encountered what one could call a bug with this project, although its a bit more ambiguous than that...

I am attempting to use MumbleSharp with a project called FiveM as the mumble server, and FiveM implements the UMurmur project into their services. Unfortunately, FiveM does not follow the typical standard of a single byte positional packet, and instead sends a 4 byte positional packet. This, in-turn, distorts the incoming audio completely and makes it inaudible. The mumble specification indicates that the positional packet can be any number of bytes long, as long as it is delimited correctly. FiveM implements the correct delimiter, but this project here does not handle the delimiter correctly.

**Comment by DrewRidley** [comment]
It appears that FiveM itself was incompatible with the Mumble spec and has been corrected.

**Comment by Meetsch** [comment]
@DrewRidley Thanks for having followed-up and closed the bug.
